## Numpy array
learn about numpy 

In [1]:
import numpy as np

### Creating array from list

In [2]:
arr_id = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_id)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [2]:
py_list = [1, 2, 3]
print("Python List multiplication:", py_list * 2)

np_array = np.array([1, 2, 3])  #Element wise multiplication
print("NumPy Array multiplication:", np_array * 2)

import time
start = time.time()
py_list = [i * 2 for i in range(1000000)]
print("\n List operation time: ",time.time() - start)


start = time.time()
np_array = np.array(1000000) * 2
print("\n Numpy operation time: ",time.time() - start)

Python List multiplication: [1, 2, 3, 1, 2, 3]
NumPy Array multiplication: [2 4 6]

 List operation time:  0.09660148620605469

 Numpy operation time:  0.0001277923583984375


### Creating array from scratch

In [3]:
zeros = np.zeros((3,4))
print("Zeros array: \n", zeros)

ones = np.ones((2,3))
print("ones array: \n",ones)

full = np.full((2,2), 7)
print("full array: \n",full)

random = np.random.random((2,3))
print("random array: \n",random)

sequence = np.arange(0,10,2)
print("sequence array: \n",sequence)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.51970289 0.12173074 0.19645238]
 [0.63932922 0.17739292 0.10338832]]
sequence array: 
 [0 2 4 6 8]


### Vector , Matrix and Tensor

In [8]:
vector = np.array([1,2,3])
print("Vector: \n",vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("matrix: \n",matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("tensor :\n ",tensor)

Vector: 
 [1 2 3]
matrix: 
 [[1 2 3]
 [4 5 6]]
tensor :
  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [27]:
arr = np.array([[1,2,3],[4,5.6,True]])
print("shape: ",arr.shape)
print("Dimension: ",arr.ndim)
print("size: ",arr.size)
print("data type: ",arr.dtype)

shape:  (2, 3)
Dimension:  2
size:  6
data type:  float64


### Array Reshaping

In [ ]:
arr = np.arange(12)
print("Original array: ",arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped array: ",reshaped)

flattened = reshaped.flatten() # convert in single line
print("\n Flattened array: ",flattened)

raveled = reshaped.ravel() # its return view instead of copy
print("\n raveled array: ",raveled)

transpose = reshaped.T
print("\n Transpose array :",transpose)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose array : [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
