## Numpy array operations

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6])
print("Basic slicing: ", arr[2:5])
print("With step: ", arr[2:5:2])
print("Negative indexing: ", arr[-3])

Basic slicing:  [3 4 5]
With step:  [3 5]
Negative indexing:  4


In [5]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Specific element: ", arr_2d[1,2])
print("Entire row: ", arr_2d[2])
print("Entire col: ", arr_2d[:,2])

Specific element:  6
Entire row:  [7 8 9]
Entire col:  [3 6 9]


## Sorting

In [8]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Original array: ", np.sort(unsorted))

np_2d_unsorted = np.array([[3, 1, 4], [1, 5, 9], [2, 6, 5]])
print("Sorted 2d array by column: \n", np.sort(np_2d_unsorted, axis=0))

Original array:  [1 1 2 3 4 5 6 9]
Sorted 2d array by column: 
 [[1 1 4]
 [2 5 5]
 [3 6 9]]


## Filter

In [9]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_numbers = numbers[numbers % 2 == 0]
print("Even numbers: ", even_numbers)

Even numbers:  [ 2  4  6  8 10]


## Filter with Mask

In [3]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mask = numbers % 2 ==0
print("Event number is: ",numbers[mask])

Event number is:  [ 2  4  6  8 10]


## Fency indexing vs np.where()

In [6]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where: ",numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where:  [ 6  7  8  9 10]


In [9]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
condition_array = np.where(numbers > 5,numbers * 2,numbers)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


## Adding and removing data

In [15]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np. concatenate((arr1,arr2))
print(combined)

delete = np.delete(arr1, 2)
print(delete)

[1 2 3 4 5 6]
[1 2]


In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c= np.array([7,8,9])

print("Compatibility shaape: ", a.shape == b.shape)

Compatibility shaape:  True


In [3]:
original = np.array([[1,2],[3,4]])
new = np.array([5,6])

with_new_row = np.vstack((original,new))
print(with_new_row)

[[1 2]
 [3 4]
 [5 6]]
